// Code generated by protoc-gen-go.
// source: proto/OTSthingy.proto
// DO NOT EDIT!

/*
Package OTSthingy is a generated protocol buffer package.

It is generated from these files:
	proto/OTSthingy.proto

It has these top-level messages:
	TimeStampRequest
	IncompleteTimeStamp
*/
package OTSthingy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TimeStampRequest struct {
	DocumentHash []byte `protobuf:"bytes,1,opt,name=document_hash,json=documentHash,proto3" json:"document_hash,omitempty"`
	WebhookUrl   string `protobuf:"bytes,2,opt,name=webhook_url,json=webhookUrl" json:"webhook_url,omitempty"`
	EmailAddress string `protobuf:"bytes,3,opt,name=email_address,json=emailAddress" json:"email_address,omitempty"`
	Label        string `protobuf:"bytes,4,opt,name=label" json:"label,omitempty"`
}

func (m *TimeStampRequest) Reset()                    { *m = TimeStampRequest{} }
func (m *TimeStampRequest) String() string            { return proto.CompactTextString(m) }
func (*TimeStampRequest) ProtoMessage()               {}
func (*TimeStampRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TimeStampRequest) GetDocumentHash() []byte {
	if m != nil {
		return m.DocumentHash
	}
	return nil
}

func (m *TimeStampRequest) GetWebhookUrl() string {
	if m != nil {
		return m.WebhookUrl
	}
	return ""
}

func (m *TimeStampRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *TimeStampRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type IncompleteTimeStamp struct {
	Ots []byte `protobuf:"bytes,1,opt,name=ots,proto3" json:"ots,omitempty"`
}

func (m *IncompleteTimeStamp) Reset()                    { *m = IncompleteTimeStamp{} }
func (m *IncompleteTimeStamp) String() string            { return proto.CompactTextString(m) }
func (*IncompleteTimeStamp) ProtoMessage()               {}
func (*IncompleteTimeStamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IncompleteTimeStamp) GetOts() []byte {
	if m != nil {
		return m.Ots
	}
	return nil
}

func init() {
	proto.RegisterType((*TimeStampRequest)(nil), "TimeStampRequest")
	proto.RegisterType((*IncompleteTimeStamp)(nil), "IncompleteTimeStamp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Timestamp service

type TimestampClient interface {
	WithCallback(ctx context.Context, in *TimeStampRequest, opts ...grpc.CallOption) (*IncompleteTimeStamp, error)
}

type timestampClient struct {
	cc *grpc.ClientConn
}

func NewTimestampClient(cc *grpc.ClientConn) TimestampClient {
	return &timestampClient{cc}
}

func (c *timestampClient) WithCallback(ctx context.Context, in *TimeStampRequest, opts ...grpc.CallOption) (*IncompleteTimeStamp, error) {
	out := new(IncompleteTimeStamp)
	err := grpc.Invoke(ctx, "/Timestamp/WithCallback", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Timestamp service

type TimestampServer interface {
	WithCallback(context.Context, *TimeStampRequest) (*IncompleteTimeStamp, error)
}

func RegisterTimestampServer(s *grpc.Server, srv TimestampServer) {
	s.RegisterService(&_Timestamp_serviceDesc, srv)
}

func _Timestamp_WithCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeStampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimestampServer).WithCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Timestamp/WithCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimestampServer).WithCallback(ctx, req.(*TimeStampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Timestamp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Timestamp",
	HandlerType: (*TimestampServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WithCallback",
			Handler:    _Timestamp_WithCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/OTSthingy.proto",
}

func init() { proto.RegisterFile("proto/OTSthingy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0x84, 0x40,
	0x14, 0xc7, 0x71, 0xb7, 0x82, 0x9d, 0x8c, 0x36, 0xdb, 0x40, 0x24, 0x28, 0xec, 0x50, 0x74, 0x50,
	0xaa, 0x5b, 0xb7, 0xe8, 0x52, 0xa7, 0x40, 0x37, 0x3a, 0xda, 0xa8, 0x0f, 0x1d, 0x76, 0x9c, 0x67,
	0xce, 0x93, 0xa5, 0x6b, 0x5f, 0x61, 0x3f, 0x5a, 0x5f, 0xa1, 0x0f, 0x92, 0x8e, 0xd6, 0x21, 0xba,
	0xcd, 0xfb, 0xfd, 0x1f, 0x3f, 0xfe, 0xf3, 0xd8, 0x51, 0xdd, 0x20, 0x61, 0xf8, 0xb4, 0x8c, 0xa9,
	0x14, 0xaa, 0x78, 0x0f, 0xcc, 0xec, 0x1d, 0x17, 0x88, 0x85, 0x84, 0x90, 0xd7, 0x22, 0xe4, 0x4a,
	0x21, 0x71, 0x12, 0xa8, 0xf4, 0x90, 0xfa, 0x1b, 0x8b, 0xcd, 0x97, 0xa2, 0x82, 0x98, 0x78, 0x55,
	0x47, 0xf0, 0xd6, 0x82, 0x26, 0xe7, 0x8c, 0xed, 0xe5, 0x98, 0xb5, 0x15, 0x28, 0x4a, 0x4a, 0xae,
	0x4b, 0xd7, 0x3a, 0xb5, 0x2e, 0xec, 0xc8, 0xfe, 0x81, 0x0f, 0x1d, 0x73, 0x4e, 0xd8, 0xee, 0x1a,
	0xd2, 0x12, 0x71, 0x95, 0xb4, 0x8d, 0x74, 0x27, 0xdd, 0xca, 0x2c, 0x62, 0x23, 0x7a, 0x6e, 0x64,
	0x6f, 0x81, 0x8a, 0x0b, 0x99, 0xf0, 0x3c, 0x6f, 0x40, 0x6b, 0x77, 0x6a, 0x56, 0x6c, 0x03, 0xef,
	0x06, 0xe6, 0x2c, 0xd8, 0xb6, 0xe4, 0x29, 0x48, 0x77, 0xcb, 0x84, 0xc3, 0xe0, 0x9f, 0xb3, 0xc3,
	0x47, 0x95, 0x61, 0x55, 0x4b, 0x20, 0xf8, 0xad, 0xe7, 0xcc, 0xd9, 0x14, 0x49, 0x8f, 0x6d, 0xfa,
	0xe7, 0xf5, 0x2b, 0x9b, 0xf5, 0xb1, 0x36, 0x71, 0xcc, 0xec, 0x17, 0x41, 0xe5, 0x3d, 0x97, 0x32,
	0xe5, 0xd9, 0xca, 0x39, 0x08, 0xfe, 0xfe, 0xcc, 0x5b, 0x04, 0xff, 0x78, 0x7d, 0xef, 0xe3, 0xf3,
	0x6b, 0x33, 0x59, 0xf8, 0xfb, 0xe1, 0x55, 0xb8, 0xee, 0x0c, 0xd9, 0x68, 0xb8, 0xb5, 0x2e, 0xd3,
	0x1d, 0x73, 0xa7, 0x9b, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x87, 0x44, 0x58, 0x71, 0x5e, 0x01,
	0x00, 0x00,
}
